#!/bin/sh
#
#  generate_secrets.sh
#  EmGestPro
#
#  Generates EmGestPro/App/PatreonSecrets.swift from the local .env file
#  (key: PATREON_OWNER_EMAIL). The generated file is gitignored and is what the
#  app compiles against at build time, so the email never has to be committed.
#
#  Runs automatically as the "Generate Patreon Secrets" pre-build phase, and
#  can also be run by hand (e.g. before `xcodegen generate` on a fresh clone):
#
#      scripts/generate_secrets.sh
#
#  If .env is missing or the key is empty, a placeholder is written and the
#  creator auto-unlock is simply disabled (same behaviour as before).

set -e

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT="$ROOT/EmGestPro/App/PatreonSecrets.swift"
ENV_FILE="$ROOT/.env"

OWNER_EMAIL=""

if [ -f "$ENV_FILE" ]; then
    # Take the last PATREON_OWNER_EMAIL=... line, strip surrounding quotes.
    OWNER_EMAIL="$(
        sed -n 's/^[[:space:]]*PATREON_OWNER_EMAIL[[:space:]]*=[[:space:]]*//p' "$ENV_FILE" |
        tail -n 1 |
        sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
    )"
fi

# Escape backslashes and quotes so the value is a valid Swift string literal.
ESCAPED_EMAIL="$(printf '%s' "$OWNER_EMAIL" | sed 's/\\/\\\\/g; s/"/\\"/g')"

TMP="$OUT.tmp"
mkdir -p "$(dirname -- "$OUT")"
cat > "$TMP" <<EOF
//
//  PatreonSecrets.swift
//  EmGestPro
//
//  AUTO-GENERATED by scripts/generate_secrets.sh — do not edit by hand.
//  Values are read from the local .env file (PATREON_OWNER_EMAIL) and injected
//  at build time. This file is gitignored; it is regenerated by the
//  "Generate Patreon Secrets" pre-build phase before every build.

/// Compile-time Patreon secrets injected from .env.
enum PatreonSecrets {
    /// The EmAppleFlagship campaign owner's Patreon email. When a signed-in
    /// user's email matches, EmGestPro Ultra unlocks automatically without a
    /// membership check. Empty means the creator auto-unlock is disabled.
    static let ownerEmail = "$ESCAPED_EMAIL"
}
EOF

# Only touch the output when the content actually changed, so Xcode doesn't
# rebuild the app on every run of the build phase.
if [ -f "$OUT" ] && cmp -s "$OUT" "$TMP"; then
    rm -f "$TMP"
else
    mv "$TMP" "$OUT"
fi

if [ -n "$OWNER_EMAIL" ]; then
    echo "generate_secrets.sh: wrote $OUT (owner email configured)"
else
    echo "generate_secrets.sh: wrote $OUT (no PATREON_OWNER_EMAIL in .env — owner unlock disabled)"
fi