#!/bin/sh
#
#  generate_secrets.sh
#  EmGestPro
#
#  Generates EmGestPro/App/PatreonSecrets.swift from the local .env file
#  (keys: PATREON_CLIENT_ID, PATREON_CLIENT_SECRET, PATREON_OWNER_EMAIL).
#  The generated file is gitignored and is what the app compiles against at
#  build time, so real credentials never have to be committed.
#
#  Runs automatically as the "Generate Patreon Secrets" pre-build phase, and
#  can also be run by hand (e.g. before `xcodegen generate` on a fresh clone):
#
#      scripts/generate_secrets.sh
#
#  If .env is missing or a key is empty, a placeholder is written for the
#  client credentials (paywall login disabled) and the creator auto-unlock is
#  disabled — same behaviour as before.

set -e

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT="$ROOT/EmGestPro/App/PatreonSecrets.swift"
ENV_FILE="$ROOT/.env"

# Read the last `KEY=value` line from .env, stripping surrounding quotes.
env_value() {
    sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" |
    tail -n 1 |
    sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

CLIENT_ID=""
CLIENT_SECRET=""
OWNER_EMAIL=""

if [ -f "$ENV_FILE" ]; then
    CLIENT_ID="$(env_value PATREON_CLIENT_ID)"
    CLIENT_SECRET="$(env_value PATREON_CLIENT_SECRET)"
    OWNER_EMAIL="$(env_value PATREON_OWNER_EMAIL)"
fi

# Keep the legacy placeholder convention so PatreonConfig.isConfigured stays
# accurate (it flags any value containing "YOUR_" as "not configured").
[ -z "$CLIENT_ID" ] && CLIENT_ID="YOUR_PATREON_CLIENT_ID"
[ -z "$CLIENT_SECRET" ] && CLIENT_SECRET="YOUR_PATREON_CLIENT_SECRET"

# Escape backslashes and quotes so the values are valid Swift string literals.
escape_swift() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}
ESCAPED_CLIENT_ID="$(escape_swift "$CLIENT_ID")"
ESCAPED_CLIENT_SECRET="$(escape_swift "$CLIENT_SECRET")"
ESCAPED_EMAIL="$(escape_swift "$OWNER_EMAIL")"

TMP="$OUT.tmp"
mkdir -p "$(dirname -- "$OUT")"
cat > "$TMP" <<EOF
//
//  PatreonSecrets.swift
//  EmGestPro
//
//  AUTO-GENERATED by scripts/generate_secrets.sh — do not edit by hand.
//  Values are read from the local .env file (PATREON_CLIENT_ID,
//  PATREON_CLIENT_SECRET, PATREON_OWNER_EMAIL) and injected at build time.
//  This file is gitignored; it is regenerated by the "Generate Patreon
//  Secrets" pre-build phase before every build.

/// Compile-time Patreon secrets injected from .env.
enum PatreonSecrets {
    /// The Patreon v2 OAuth client ID. Without it the paywall can't start the
    /// sign-in flow (PatreonConfig.isConfigured is false).
    static let clientID = "$ESCAPED_CLIENT_ID"

    /// The Patreon v2 OAuth client secret, used to exchange the OAuth code for
    /// a token. Never commit this — it lives in .env and is injected at build.
    static let clientSecret = "$ESCAPED_CLIENT_SECRET"

    /// The EmAppleFlagship campaign owner's Patreon email. When a signed-in
    /// user's email matches, EmGestPro Ultra unlocks automatically without a
    /// membership check. Empty means the creator auto-unlock is disabled.
    static let ownerEmail = "$ESCAPED_EMAIL"
}
EOF

# Only touch the output when the content actually changed, so Xcode doesn't
# rebuild the app on every run of the build phase.
if [ -f "$OUT" ] && cmp -s "$OUT" "$TMP"; then
    rm -f "$TMP"
else
    mv "$TMP" "$OUT"
fi

if [ -n "$OWNER_EMAIL" ] || [ "$CLIENT_ID" != "YOUR_PATREON_CLIENT_ID" ] || [ "$CLIENT_SECRET" != "YOUR_PATREON_CLIENT_SECRET" ]; then
    echo "generate_secrets.sh: wrote $OUT (secrets configured)"
else
    echo "generate_secrets.sh: wrote $OUT (no Patreon credentials in .env — paywall login disabled)"
fi